name: build
on:
  push:
    branches:
      - master 
      - 'releases/**'
  workflow_dispatch:

jobs:
    call-workflow-in-another-repo:
       uses: RakeshAMD/.github/.github/workflows/deploy-workflow.yaml@main
       secrets: inherit
